In [1]:
from numpy import array
A = array([[1,2,3], [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
B = array([[1,2,3], [4,5,6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
C = A+B
C

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [6]:
C = A-B+0.5
C

array([[0.5, 0.5, 0.5],
       [0.5, 0.5, 0.5]])

In [7]:
C = A*B

In [8]:
C

array([[ 1,  4,  9],
       [16, 25, 36]])

In [9]:
C = A/B
C

array([[1., 1., 1.],
       [1., 1., 1.]])