## 2.1 Square Matrix

The number of rows (n) is equivalent to the number of
columns (m).

In [1]:
from numpy import array

a = array([[1,2,3], [1,2,3], [1,2,3]])
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

## 2.2 Symmetric Matrix

A symmetric matrix is a type of square matrix where the top-right triangle is the same as the bottom-left triangle.

A symmetric matrix is always square and equal to its own transpose.

In [2]:
b = array([[1,2,3,4,5], [2,1,2,3,4], [3,2,1,2,3], [4,3,2,1,2], [5,4,3,2,1]])
print(b)

[[1 2 3 4 5]
 [2 1 2 3 4]
 [3 2 1 2 3]
 [4 3 2 1 2]
 [5 4 3 2 1]]


## 2.3 Triangular Matrix

A triangular matrix is a type of square matrix that has all values in the upper-right or lower-left of the matrix with the remaining elements filled with zero values. 

A triangular matrix with values only above the main diagonal is called an upper triangular matrix.

Whereas, a triangular matrix with values only below the main diagonal is called a lower triangular matrix.

In [4]:
# triangular matrices
from numpy import array
from numpy import tril
from numpy import triu

#define a square matrix
M = array([[1,2,3],[1,2,3],[1,2,3]])

print(M)

lower = tril(M)
print(lower)

upper = triu(M)
print(upper)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 0 0]
 [1 2 0]
 [1 2 3]]
[[1 2 3]
 [0 2 3]
 [0 0 3]]


## 2.4 Diagonal Matrix

In [7]:
# diagonal matrix
from numpy import diag
# define square matrix

M = array([[1,2,3],[1,2,3],[1,2,3]])

print(M)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [8]:
# extract diagonal vector
d = diag(M)
print(d)

[1 2 3]


In [9]:
# create diagonal matrix from vector
D = diag(d)
print(D)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


## 2.5 Identity Matrix

An identity matrix is a square matrix that does not change a vector when multiplied.

In [13]:
# identity matrix
from numpy import identity
I = identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 2.6 Orthogonal Matrix

Two vectors are orthogonal when their dot product equals zero.

v.w = 0
<br>
v.w<sup>T</sup> = 0

This is intuitive when we consider that one line is orthogonal with another if it is perpendicular
to it.

### Q<sup>T</sup>.Q = Q.Q<sup>T</sup> = I

where Q is the orthogonal matrix
Q<sup>T</sup> is the transpose of Q
I is the identity matrix

A matrix is orthogonal if its transpose is equal to its inverse.

### Q<sup>T</sup> = Q<sup>-1</sup>

Orthogonal matrices are used a lot for linear transformations, such as reflections and
permutations. A simple 2 × 2 orthogonal matrix is listed below, which is an example of a
reflection matrix or coordinate reflection.


In [14]:
from numpy.linalg import inv

#define orthogonal matrix
Q = array([[1,0], [0, -1]])

print(Q)

[[ 1  0]
 [ 0 -1]]


In [16]:
# inverse equivalence
V=inv(Q)
V

array([[ 1.,  0.],
       [-0., -1.]])

In [17]:
Q.T

array([[ 1,  0],
       [ 0, -1]])

In [18]:
# identity equivaence
I = Q.dot(Q.T)
print(I)

[[1 0]
 [0 1]]


#### numpy.diag

In [21]:
import numpy as np

x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
np.diag(x)

array([0, 4, 8])

In [23]:
np.diag(x, k=1)

array([1, 5])

In [24]:
np.diag(x, k=-1)

array([3, 7])

In [25]:
np.diag(x, k=2)

array([2])

In [27]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])