## 3.1 Transpose

In [1]:
from numpy import array

# transpose matrix
A = array([[1,2], [3,4], [5,6]])
print(A)

#tanspose
C = A.T
C

[[1 2]
 [3 4]
 [5 6]]


array([[1, 3, 5],
       [2, 4, 6]])

## 3.2 Inverse

Matrix inversion is a process that finds another matrix that when multiplied with the matrix, results in an identity matrix. Given a matrix A, find matrix B, such that <br> 
AB = I<sup>n</sup> or BA = I<sup>n</sup>.

In [2]:
from numpy.linalg import inv

#define matrix
A = array([[1.0, 2.0],
           [3.0, 4.0]])
print(A)

#invert matrix
B=inv(A)
print(B)

# multiply A and B
I = A.dot(B)
print(I)

[[1. 2.]
 [3. 4.]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


## 3.3 Trace

A trace of a square matrix is the sum of the values on the main diagonal of the matrix (top-left
to bottom-right).


In [3]:
from numpy import trace

In [4]:
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [5]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# Calculate Trace
B = trace(A)
B

15

## 3.4 Determinant

The determinant of a square matrix is a scalar representation of the volume of the matrix

The determinant describes the relative geometry of the vectors that make up the rows of the matrix. More specifically, the determinant of a matrix A tells you the volume of a box with sides given by rows of A.

the determinant is the product of all the eigenvalues of the matrix.

The determinant of a square matrix is a single number. [...] It tells immediately
whether the matrix is invertible. The determinant is a zero when the matrix has no
inverse.

In [10]:
from numpy.linalg import det

print(A)

# calculating Determinant
B = det(A)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
-9.51619735392994e-16


In [11]:
c = det([[1,2], [3,4]])

In [12]:
c

-2.0000000000000004

## 3.5 Rank

The rank of a matrix is the estimate of the number of linearly independent rows or columns in a matrix.

The rank of a matrix is the estimate of the number of linearly independent rows or columns in a matrix.

In [16]:
# vector rank
from numpy.linalg  import matrix_rank

#rank
v1 = array([1,2,3])   #line
print(v1)
matrix_rank(v1)

[1 2 3]


1

In [17]:
v2 = array([0,0,0,0,0])   #point
print(v2)
matrix_rank(v2)

[0 0 0 0 0]


0

In [19]:
#rank 0
M0 = array([[0,0], [0,0]])
print(M0)

matrix_rank(M0)

[[0 0]
 [0 0]]


0

In [21]:
#rank 1
M1 = array([[1,2], [1,2]])
print(M1)
matrix_rank(M1)

[[1 2]
 [1 2]]


1

In [22]:
# rank 2
M2 = array([[1,2], [3,4]])
print(M2)
matrix_rank(M2)

[[1 2]
 [3 4]]


2

In [25]:
A = array([
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

matrix_rank(A)

2