In [1]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### trace(), returns the sum along the diagonals

In [3]:
np.trace(np.eye(3))

3.0

In [4]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [6]:
a = np.arange(8).reshape((2,2,2))
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [7]:
np.trace(a)

array([6, 8])

In [8]:
np.diagonal(a)

array([[0, 6],
       [1, 7]])

In [12]:
np.diagonal(np.arange(6).reshape(2,3))

array([0, 4])

In [13]:
a = np.arange(8).reshape(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [14]:
np.diagonal(a)

array([[0, 6],
       [1, 7]])

In [16]:
a[:,:,0]

array([[0, 2],
       [4, 6]])

In [17]:
a[:,:,1]

array([[1, 3],
       [5, 7]])

In [18]:
a.diagonal(0,0,1)

array([[0, 6],
       [1, 7]])