In [1]:
#There are primarily two types of sparse matrices that we use:
#

In [2]:
import numpy as np

In [3]:
from scipy.sparse import csr_matrix

In [8]:
csr_matrix((3,4), dtype=np.int8)

<3x4 sparse matrix of type '<class 'numpy.int8'>'
	with 0 stored elements in Compressed Sparse Row format>

In [9]:
csr_matrix((3,4), dtype=np.int8).toarray()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [10]:
row = np.array([0,0,1,2,2,2])
row

array([0, 0, 1, 2, 2, 2])

In [12]:
col = np.array([0,2,2,0,1,2])
col

array([0, 2, 2, 0, 1, 2])

In [13]:
data = np.array([1,2,3,4,5,6])
data

array([1, 2, 3, 4, 5, 6])

In [16]:
csr_matrix((data, (row, col)), shape=(3,3)).toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]], dtype=int32)

In [20]:
indptr = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])

In [22]:
csr_matrix((data, indices, indptr), shape=(3,3)).toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

In [25]:
# Duplicate entries are summed together:

In [23]:
row = np.array([0, 1, 2, 0])
col = np.array([0, 1, 1, 0])
data = np.array([1, 2, 4, 8])

In [24]:
csr_matrix((data, (row, col)), shape=(3, 3)).toarray()

array([[9, 0, 0],
       [0, 2, 0],
       [0, 4, 0]], dtype=int32)

In [26]:
#Equivalent to np.prod(a.shape), i.e., the product of the array’s dimensions.

In [27]:
import numpy as np
x = np.zeros((3,5,2), dtype=np.complex128)

In [28]:
x.size

30

In [29]:
np.prod(x.shape)

30