#### Matrices that contain mostly zero values are called sparse, distinct from matrices where most of the values are non-zero, called dense

The sparsity of a matrix can be quantified with a score, which is the number of zero values
in the matrix divided by the total number of elements in the matrix.

In [2]:
#sparse matrix
from numpy import array
from scipy.sparse import csr_matrix

#create dense matrix

A=array([
    [1,0,0,1,0,0],
    [0,0,2,0,0,1],
    [0,0,0,2,0,0]])

print(A)

#convert to sparse matrix (CSR method)
S=csr_matrix(A)
print(S)

# reconstruct dense matrix
B=S.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2
[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [3]:
## NumPy does not provide a function to calculate the sparsity of a matrix.
## sparsity of a matrix = number of zero values in the matrix divided by the total number of elements in the matrix

## sparsity = 1.0 - count_nonzero(A) / A.size

In [5]:
# sparsity calculation
from numpy import array
from numpy import count_nonzero

#create dense matrix

print(A)

#calculate sparsity
sparsity = 1.0 - count_nonzero(A)/A.size
print(sparsity)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]
0.7222222222222222
