### Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

### That tensors are a generalization of matrices and are represented using n-dimensional arrays.

A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional
array.


In [1]:
# create tensor
from numpy import array
T = array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[11,12,13], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]])

print(T)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [2]:
print(T.shape)

(3, 3, 3)


## 5. Tensor Arithmetic

### 5.1 Tensor Addition

In [3]:
# tensor addition

In [4]:
#define first tensor
A = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])

print(A)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [6]:
#define first tensor
B = array([
[[1,2,3], [4,5,6], [7,8,9]],
[[11,12,13], [14,15,16], [17,18,19]],
[[21,22,23], [24,25,26], [27,28,29]]])

print(B)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [8]:
# add tensors

C = A+B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


## 5.2 Tensor Product

The tensor product operator is often denoted as a circle with a small x in the middle. We will
denote it here as ⊗. Given a tensor A with q dimensions and tensor B with r dimensions, the
product of these tensors will be a new tensor with the order of q + r or, said another way, q + r
dimensions.

In [9]:
# a=2*1 and b=2*1 the resultent matrix will be 2*2

In [10]:
# a=2*2 and b=2*2 the resultent matrix will be 4*4

In [11]:
#To calculate the tensor product, also called the tensor dot product in NumPy, the axis must be set to 0.

In [12]:
# tensor product
from numpy import array
from numpy import tensordot

# first vector
a = array([1,2])
print(a)

# second vector
b=array([3,4])
print(b)

[1 2]
[3 4]


In [13]:
c = tensordot(a, b, axes=0)
print(c)

[[3 4]
 [6 8]]


In [15]:
a = array([[1,2], [3,4]])
print(a)

b=array([[1,2], [3,4]])
print(b)

c = tensordot(a, b, axes=0)
print(c)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[[[ 1  2]
   [ 3  4]]

  [[ 2  4]
   [ 6  8]]]


 [[[ 3  6]
   [ 9 12]]

  [[ 4  8]
   [12 16]]]]
