In [10]:
# KNN imputation transform for the horse colic dataset
from numpy import isnan
from pandas import read_csv
from sklearn.impute import KNNImputer

In [11]:
# loading dataset
dataframe = read_csv('horse-colic.csv', header=None, na_values='?')
dataframe.head()

0   1        2     3      4     5    6    7    8    9   ...    18    19  \
0  2.0   1   530101  38.5   66.0  28.0  3.0  3.0  NaN  2.0  ...  45.0   8.4   
1  1.0   1   534817  39.2   88.0  20.0  NaN  NaN  4.0  1.0  ...  50.0  85.0   
2  2.0   1   530334  38.3   40.0  24.0  1.0  1.0  3.0  1.0  ...  33.0   6.7   
3  1.0   9  5290409  39.1  164.0  84.0  4.0  1.0  6.0  2.0  ...  48.0   7.2   
4  2.0   1   530255  37.3  104.0  35.0  NaN  NaN  6.0  2.0  ...  74.0   7.4   

    20   21   22  23     24  25  26  27  
0  NaN  NaN  2.0   2  11300   0   0   2  
1  2.0  2.0  3.0   2   2208   0   0   2  
2  NaN  NaN  1.0   2      0   0   0   1  
3  3.0  5.3  2.0   1   2208   0   0   1  
4  NaN  NaN  2.0   2   4300   0   0   2  

[5 rows x 28 columns]

In [12]:
# split into input and output elements
data = dataframe.values
ix = [i for i in range(data.shape[1]) if i != 23]
x, y = data[:, ix], data[:, 23]

In [13]:
data

array([[2.00000e+00, 1.00000e+00, 5.30101e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.34817e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [2.00000e+00, 1.00000e+00, 5.30334e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       ...,
       [1.00000e+00, 1.00000e+00, 5.29386e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.30612e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.34618e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00]])

In [15]:
x

array([[2.00000e+00, 1.00000e+00, 5.30101e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.34817e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [2.00000e+00, 1.00000e+00, 5.30334e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       ...,
       [1.00000e+00, 1.00000e+00, 5.29386e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.30612e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.34618e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00]])

In [16]:
y

array([2., 2., 2., 1., 2., 2., 1., 1., 1., 2., 1., 1., 2., 2., 1., 1., 2.,
       2., 1., 2., 1., 2., 1., 1., 1., 2., 1., 2., 2., 2., 1., 1., 1., 1.,
       1., 1., 2., 1., 2., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1., 2., 2.,
       1., 2., 2., 1., 1., 1., 1., 1., 1., 2., 2., 1., 2., 1., 1., 1., 2.,
       2., 2., 1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1.,
       2., 1., 1., 2., 2., 1., 1., 2., 1., 2., 1., 1., 2., 2., 2., 2., 1.,
       2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1.,
       2., 1., 1., 2., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 2., 2., 2., 2., 1., 2., 2., 1., 1., 1., 1., 2., 2., 1., 1.,
       2., 1., 2., 2., 1., 2., 2., 1., 1., 2., 1., 1., 2., 2., 2., 1., 1.,
       2., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 2., 1., 2., 2., 1., 1.,
       1., 1., 1., 1., 2., 1., 1., 2., 2., 2., 1., 2., 2., 1., 1., 1., 2.,
       1., 2., 1., 1., 1., 2., 1., 1., 2., 1., 2., 1., 2., 1., 1., 1., 2.,
       1., 1., 1., 1., 2.

In [17]:
# summarizing total missing
print('Missing: %d' % sum(isnan(x).flatten()))

Missing: 1605


In [18]:
# define imputer
imputer = KNNImputer()

In [19]:
#fit on the dataset
imputer.fit(x)

KNNImputer()

In [20]:
# transforming the dataset
xtrans = imputer.transform(x)

In [21]:
xtrans

array([[2.00000e+00, 1.00000e+00, 5.30101e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.34817e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [2.00000e+00, 1.00000e+00, 5.30334e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       ...,
       [1.00000e+00, 1.00000e+00, 5.29386e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.30612e+05, ..., 0.00000e+00,
        0.00000e+00, 1.00000e+00],
       [1.00000e+00, 1.00000e+00, 5.34618e+05, ..., 0.00000e+00,
        0.00000e+00, 2.00000e+00]])

In [24]:
#summarizing total missing
print('Missing: %d' % sum(isnan(xtrans).flatten()))

Missing: 0


In [25]:
from numpy import mean
from numpy import std
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import KNNImputer
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.pipeline import Pipeline

In [26]:
# defining modeling pipeline
model = RandomForestClassifier()
imputer = KNNImputer()
pipeline = Pipeline(steps=[('i', imputer), ('m', model)])
# define model evaluation
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [28]:
# evaluate model
scores = cross_val_score(pipeline, x, y, scoring='accuracy', cv=cv, n_jobs=-1)
print('Mean Accuracy: %.3f (%.3f)' % (mean(scores), std(scores)))

Mean Accuracy: 0.860 (0.055)


In [30]:
type(x)

numpy.ndarray

In [31]:
import pandas as pd

In [35]:
df = pd.DataFrame(xtrans[:, :])

In [36]:
df.head()

0    1          2     3      4     5    6    7    8    9   ...   17    18  \
0  2.0  1.0   530101.0  38.5   66.0  28.0  3.0  3.0  2.2  2.0  ...  5.0  45.0   
1  1.0  1.0   534817.0  39.2   88.0  20.0  3.0  2.0  4.0  1.0  ...  2.0  50.0   
2  2.0  1.0   530334.0  38.3   40.0  24.0  1.0  1.0  3.0  1.0  ...  1.0  33.0   
3  1.0  9.0  5290409.0  39.1  164.0  84.0  4.0  1.0  6.0  2.0  ...  3.2  48.0   
4  2.0  1.0   530255.0  37.3  104.0  35.0  3.0  2.6  6.0  2.0  ...  4.2  74.0   

     19   20    21   22       23   24   25   26  
0   8.4  2.2  3.96  2.0  11300.0  0.0  0.0  2.0  
1  85.0  2.0  2.00  3.0   2208.0  0.0  0.0  2.0  
2   6.7  2.2  5.18  1.0      0.0  0.0  0.0  1.0  
3   7.2  3.0  5.30  2.0   2208.0  0.0  0.0  1.0  
4   7.4  2.4  2.80  2.0   4300.0  0.0  0.0  2.0  

[5 rows x 27 columns]

In [37]:
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
5     0
6     0
7     0
8     0
9     0
10    0
11    0
12    0
13    0
14    0
15    0
16    0
17    0
18    0
19    0
20    0
21    0
22    0
23    0
24    0
25    0
26    0
dtype: int64

In [39]:
dfy = pd.DataFrame(y)

In [40]:
dfy.isnull().sum()

0    0
dtype: int64