## 2.1 Vector L^1 Norm

The length of a vector can be calculated using the L 1 norm, where the 1 is a superscript of the L.


The notation for the L^1 norm of a vector is ||v||<sub>1</sub>

 As such, this
length is sometimes called the taxicab norm or the Manhattan norm.
L<sup>1</sup>(v) = ||v||<sub>1</sub>

Where: ||v||1 = |a1| + |a2| + |a3|

In [48]:
# https://www.datasciencelearner.com/np-linalg-norm-numpy-find-norms/#:~:text=Finding%20the%20norms%20using%20np%20linalg%20norm%20method.,Calculate%20the%20np%20linalg%20norm%20of%20the%20array
# https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.linalg.norm.html

The L1 norm of a vector can be calculated in NumPy using the norm() function with a parameter to specify the norm order, in this case 1.

In [2]:
# Vector L1 norm
from numpy import array
from numpy.linalg import norm

#define vector
a = array([1,2,3])
print(a)

l1 = norm(a,1)
print(l1)

[1 2 3]
6.0


## 2.2 Vector L^2 Norm

The length of a vector can be calculated using the L<sup>2</sup> norm, where the 2 is a superscript of the
L. The notation for the L<sup>2</sup> norm of a vector is ||v||<sub>2</sub> where 2 is a subscript.

||v<sub>2</sub>|| = sqrt(a<sub>1</sub><sup>2</sup>+a<sub>2</sub><sup>2</sup>+a<sub>3</sub><sup>2</sup>)

In [6]:
# vector L2 norm
from numpy import array
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)

#calculate norm
l2 = norm(a)
l2

[1 2 3]


3.7416573867739413

## 8.5 Vector Max Norm

The length of a vector can be calculated using the maximum norm, also called max norm. Max norm of a vector is referred to as L<sup>inf</sup> where inf is a superscript and can be represented with the infinity symbol. The notation for max norm is ||v||<sub>inf</sub> , where inf is a subscript.

L<sup>inf</sup>(v) = ||v||<sub>inf</sub>

The max norm is calculated as returning the maximum value of the vector, hence the name.
||v||<sub>inf</sub> = max a1, a2, a3 

In [8]:
#vector max norm
from math import inf
#define vector

a = array([1,2,3])
print(a)

#calculate norm
maxnorm = norm(a, inf)
print(maxnorm)

[1 2 3]
3.0


In [14]:
import numpy as np
from numpy import linalg as LA
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
np.arange(9) - 4

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [17]:
a = np.arange(9) - 4
a

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [18]:
b = a.reshape((3,3))
b

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [19]:
LA.norm(a)

7.745966692414834

In [20]:
LA.norm(b)

7.745966692414834

### 1D

In [44]:
array_1d = np.array([10,20,30,40,50,60,70,80])

In [45]:
LA.norm(array_1d, 1) # l1

360.0

In [46]:
LA.norm(array_1d)   #l2

142.828568570857

In [47]:
LA.norm(array_1d, inf)

80.0

### 2D

In [57]:
array_2d = np.array([[10,20,30,40],[50,60,70,80]])
array_2d

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [58]:
LA.norm(array_2d, 1)

120.0

In [59]:
LA.norm(array_2d)

142.828568570857

In [60]:
LA.norm(array_2d, inf)

260.0

In [32]:
LA.norm?

In [61]:
LA.norm(array_2d, axis=1)

array([ 54.77225575, 131.90905958])

In [35]:
LA.norm(array_2d, 'fro')

196.21416870348583

In [50]:
arr = array([[-1, 3, 1],
            [3, -4, 7]])
arr

array([[-1,  3,  1],
       [ 3, -4,  7]])

In [51]:
LA.norm(arr)

9.219544457292887

In [53]:
arr = array([[1,2],
            [3,4]])
arr

array([[1, 2],
       [3, 4]])

In [54]:
LA.norm(arr)

5.477225575051661

In [55]:
arr = array([[1,2,3,4],
            [1,2,3,4]])

In [56]:
LA.norm(arr)

7.745966692414834