#### Matrix decompositions are methods that reduce a matrix into constituent parts that make it easier to calculate more complex matrix operations.

Matrix decomposition
methods, also called matrix factorization methods, are a foundation of linear algebra in computers,
even for basic operations such as solving systems of linear equations, calculating the inverse, and
calculating the determinant of a matrix.

## 1.1 LU Decomposition

A = L.U

where A:- the square matrix
      L:- the lower triangle matrix
      U:- the upper triangle matrix.

A variation of this decomposition that is numerically more stable to solve in practice is called the LUP decomposition, or the LU decomposition with partial pivoting.

A = L.U.P
P:- 

In [1]:
# LU decomposition
from numpy import array
from scipy.linalg import lu

# square matrix
A = array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]])

print(A)

# factorize
P, L, U = lu(A)
print(P)
print(L)
print(U)

#reconstruct
B = P.dot(L).dot(U)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


## 1.2 QR Decomposition

The QR decomposition is for n × m matrices (not limited to square matrices) and decomposes
a matrix into Q and R components.

A = Q · R 

Where A is the matrix that we wish to decompose, Q a matrix with the size m × m, and R is
an upper triangle matrix with the size m × n. The QR decomposition is found using an iterative
numerical method that can fail for those matrices that cannot be decomposed, or decomposed
easily. Like the LU decomposition, the QR decomposition is often used to solve systems of
linear equations, although is not limited to square matrices.

In [5]:
# QR decomposition

from numpy import array
from numpy.linalg import qr

# define rectangular matrix
A = array([
    [1, 2],
    [3, 4],
    [5, 6]])

print(A)

#factorize
Q, R = qr(A, 'complete')
print(Q)
print(R)

#reconstruct

B = Q.dot(R)
print(B)

[[1 2]
 [3 4]
 [5 6]]
[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]
[[1. 2.]
 [3. 4.]
 [5. 6.]]


## 1.3 Cholesky Decomposition

The Cholesky decomposition is for square symmetric matrices where all values are greater than zero, so-called positive definite matrices.

A = L.L<sup>T</sup>
<br> or <br>
A = U.U<sup>T</sup>

where L is the lower triangular matrix and L<sup>T</sup> is the transpose of L.

In [6]:
# cholesky decomposition
from numpy.linalg import cholesky

# symmetrical matrix

A=array([[2,1,2],
         [1,2,1],
         [1,1,2]])

print(A)

#factorize
L = cholesky(A)
print(L)

# reconstruct
B=L.dot(L.T)
print(B)

[[2 1 2]
 [1 2 1]
 [1 1 2]]
[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


In [4]:
A = np.array([[1,-2j],[2j,5]])
A

array([[ 1.+0.j, -0.-2.j],
       [ 0.+2.j,  5.+0.j]])

In [5]:
L = np.linalg.cholesky(A)

In [6]:
L

array([[1.+0.j, 0.+0.j],
       [0.+2.j, 1.+0.j]])

In [2]:
import numpy as np

a= np.random.randn(9, 6)
print(a)

[[ 0.06858457 -0.37619781 -0.07233413  0.02307353 -0.97836963  0.09028585]
 [-1.57665461  0.94158667  0.58166653  0.29713299 -0.63477234  1.90405164]
 [-0.13982739  2.17387262 -1.03673909  0.65102143  0.69090307  0.18816731]
 [ 0.94094325  2.17047681 -1.23101137  1.24446061 -0.9776402   0.04021565]
 [ 1.1827741  -1.16744083 -0.8664867   0.70146739  0.29023714 -0.79777224]
 [-0.51388965 -0.37167475 -0.45728795 -1.62000446  0.91791281 -2.04143351]
 [ 0.97302945  0.67393625  1.74109075 -0.4876927   0.26403862  0.63721187]
 [ 0.49861991 -0.57048562  0.05566542  0.47575775  0.01033172  0.61924531]
 [-0.06008644  1.19204306  1.10000928 -0.01649523 -0.36309462 -0.10077399]]


In [11]:
q, r = np.linalg.qr(a)

In [12]:
q

array([[-0.3322732 , -0.07672056, -0.00549582, -0.27758158, -0.37406854,
         0.01102795],
       [-0.43846592, -0.29453402,  0.03779968, -0.4683623 ,  0.10288891,
         0.44842422],
       [-0.07478883, -0.25090279, -0.30914198, -0.45104857,  0.20003805,
        -0.22623488],
       [ 0.05439914,  0.50875332,  0.47334909, -0.1720553 ,  0.04941352,
         0.11056496],
       [ 0.50903695, -0.51193751,  0.05833594, -0.09019337, -0.47168549,
        -0.19454735],
       [-0.43988557, -0.36986836,  0.23467115,  0.43747819,  0.34373044,
        -0.42611046],
       [-0.25864306, -0.10744483, -0.15951047,  0.50254721, -0.43122509,
         0.48784189],
       [ 0.2724912 , -0.41439798,  0.57495127,  0.01776177,  0.25805307,
         0.39712697],
       [ 0.30825948, -0.05855616, -0.51422434,  0.1347078 ,  0.4624342 ,
         0.34679813]])

In [13]:
r

array([[ 2.8740027 , -0.38696902,  0.350633  , -0.69949445,  0.33636411,
        -1.51355363],
       [ 0.        ,  2.71305052, -1.43311617, -0.97714625, -1.16787123,
        -2.40259554],
       [ 0.        ,  0.        ,  2.56747122, -1.35443367,  0.47558895,
        -0.10339457],
       [ 0.        ,  0.        ,  0.        ,  4.47350242,  0.1636203 ,
         1.69484992],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  2.69903581,
         1.48009136],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        -1.82096923]])

In [14]:
np.allclose(a, np.dot(q, r))

True

In [16]:
r2 = np.linalg.qr(a, mode='r')
r2

array([[ 2.8740027 , -0.38696902,  0.350633  , -0.69949445,  0.33636411,
        -1.51355363],
       [ 0.        ,  2.71305052, -1.43311617, -0.97714625, -1.16787123,
        -2.40259554],
       [ 0.        ,  0.        ,  2.56747122, -1.35443367,  0.47558895,
        -0.10339457],
       [ 0.        ,  0.        ,  0.        ,  4.47350242,  0.1636203 ,
         1.69484992],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  2.69903581,
         1.48009136],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        -1.82096923]])

In [19]:
r3 = np.linalg.qr(a, mode='economic')
print(r3)

[[ 2.8740027  -0.38696902  0.350633   -0.69949445  0.33636411 -1.51355363]
 [ 0.32911112  2.71305052 -1.43311617 -0.97714625 -1.16787123 -2.40259554]
 [ 0.05613626  0.19427953  2.56747122 -1.35443367  0.47558895 -0.10339457]
 [-0.04083182 -0.39835097 -0.37135748  4.47350242  0.1636203   1.69484992]
 [-0.3820815   0.42642217 -0.02988631  0.03154685  2.69903581  1.48009136]
 [ 0.3301767   0.27144194 -0.1714618  -0.3878235  -0.2979119  -1.82096923]
 [ 0.19413665  0.07291553  0.12254318 -0.42798185  0.18431986 -0.38544908]
 [-0.20453102  0.33884424 -0.42566955  0.04458341 -0.10042556 -0.04108868]
 [-0.23137858  0.06011864  0.39336568 -0.16050305 -0.18876544 -0.2410044 ]]


<ipython-input-19-cf355f26fd29>:1: DeprecationWarning: The 'economic' option is deprecated.
  r3 = np.linalg.qr(a, mode='economic')


In [21]:
np.allclose(r, r2) # mode='r' returns the same r as mode='full'

True

In [22]:
# But only triu parts are guaranteed equal when mode='economic'

In [23]:
np.allclose(r, np.triu(r3[:6,:6], k=0))

True

In [28]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])