## 2.1 Eigendecompositon of a Matrix

Eigendecomposition of a matrix is a type of decomposition that involves decomposing a square matrix into a set of eigenvectors and eigenvalues.

A vector is an eigenvector of a matrix if it satisfies the following equation.
<br>
A · v = λ · v <br>
This is called the eigenvector.

where:This is called the eigenvalue equation, where A is the parent square matrix that we are
decomposing, v is the eigenvector of the matrix, and λ is the lowercase Greek letter lambda and
represents the eigenvalue scalar.

## 2.2 Calculation of Eigendecomposition

In [1]:
# eigendecomposition
from numpy import array
from numpy.linalg import eig

# define matrix
A = array([[1,2,3],
          [4,5,6],
          [7,8,9]])

print(A)

#factorize
values, vectors = eig(A)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -3.38433605e-16]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## 2.3 Confirm an Eigenvector and Eigenvalue

In [3]:
# define matrix
A = array([[1,2,3],
          [4,5,6],
          [7,8,9]])

#factorize
values, vectors = eig(A)
values

array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16])

In [4]:
vectors

array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]])

In [5]:
# confirm first eigenvector
B= A.dot(vectors[:, 0])
print(B)

[ -3.73863537  -8.46653421 -13.19443305]


In [6]:
C = vectors[:, 0]* values[0]
print(C)

[ -3.73863537  -8.46653421 -13.19443305]


## 2.4 Reconstruct Matrix

In [11]:
from numpy.linalg import inv
from numpy import diag
print(A)

#factorize
values, vectors = eig(A)

#create matrix from eigenvectors
Q=vectors
#create inverse of eigenvectors matrix
R=inv(Q)
#create diagonal matrix from eigenvalues
L= diag(values)
B=Q.dot(L).dot(R)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
