## numpy.linalg.eig

In [4]:
from numpy import linalg as LA
import numpy as np

In [5]:
w, v = LA.eig(np.diag((1,2,3)))

In [6]:
w

array([1., 2., 3.])

In [7]:
v

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
w, v = LA.eig(np.array([[1, -1], [1, 1]]))
w

array([1.+1.j, 1.-1.j])

In [9]:
v

array([[0.70710678+0.j        , 0.70710678-0.j        ],
       [0.        -0.70710678j, 0.        +0.70710678j]])

In [10]:
a = np.array([[1, 1j], [-1j, 1]])
w, v = LA.eig(a)
w

array([2.+0.j, 0.+0.j])

In [11]:
v

array([[0.        +0.70710678j, 0.70710678+0.j        ],
       [0.70710678+0.j        , 0.        +0.70710678j]])

## numpy.diag

In [12]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
np.diag(x)

array([0, 4, 8])

In [14]:
np.diag(x, k=1)

array([1, 5])

In [15]:
np.diag(x, k=-1)

array([3, 7])

In [16]:
np.diag(np.diag(x))

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

## numpy.dot

In [17]:
np.dot(3, 4)

12

In [18]:
np.dot([2j, 3j], [2j, 3j])

(-13+0j)

In [19]:
a = [[1,0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [20]:
a = np.arange(3*4*5*6).reshape((3,4,5,6))
b = np.arange(3*4*5*6)[::-1].reshape((5,4,6,3))
np.dot(a, b)[2,3,2,1,2,2]

499128

In [21]:
sum(a[2,3,2,:]* b[1,2,:,2])

499128

## numpy.linalg.inv

In [22]:
from numpy.linalg import inv

In [23]:
a = np.array([[1., 2.], [3., 4.]])
ainv = inv(a)
ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [24]:
np.allclose(np.dot(a, ainv), np.eye(2))

True

In [25]:
np.allclose(np.dot(ainv, a), np.eye(2))

True

In [26]:
# if a is a matrix object, then the return value ia a matrix as well

In [28]:
ainv = inv(np.matrix(a))
ainv

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [29]:
# inverse of several matrix can be computed at once

In [30]:
a = np.array([[[1., 2.], [3., 4.]], [[1, 3], [3, 5]]])

In [31]:
inv(a)

array([[[-2.  ,  1.  ],
        [ 1.5 , -0.5 ]],

       [[-1.25,  0.75],
        [ 0.75, -0.25]]])