it is often used
in a wide array of applications including compressing, denoising, and data reduction.

the Singular Value Decomposition (SVD) of a matrix is a factorization of that matrix into three matrices.

The diagonal values in the Σ matrix are known as the singular values of the original matrix
A.

The columns of the U matrix are called the left-singular vectors of A, and the columns
of V are called the right-singular vectors of A.

In [2]:
from numpy import array
from scipy.linalg import svd

A = array([[1, 2], 
           [3, 4],
           [5,6]])

# factorize
U, s, v = svd(A)
print(U)
print(s)
print(v)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
[9.52551809 0.51430058]
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [9]:
u1, s1, v1 = svd(array([[5, -1], [5, 7]]))
print(array([[5, 5], [-1, 7]]))
print(u1)
print(s1)
print(v1)

[[ 5  5]
 [-1  7]]
[[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
[8.94427191 4.47213595]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


## 3.2 Reconstruct Matrix

The U, s, and V
elements returned from the svd() cannot be multiplied directly. The s vector must be converted
into a diagonal matrix using the diag() function.

In [11]:
# reconstruct rectangular matrix from svd.
from numpy import zeros
from numpy import diag

A = array([[1, 2], 
           [3, 4],
           [5,6]])

#factorize
U, s, v =  svd(A)

# create m x n sigma matrix
Sigma = zeros((A.shape[0], A.shape[1]))
Sigma

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
# populate Sigma with n x n diagonal matrix
Sigma[:A.shape[1], :A.shape[1]] = diag(s)
Sigma

array([[9.52551809, 0.        ],
       [0.        , 0.51430058],
       [0.        , 0.        ]])

In [17]:
# reconstruct matrix
B = U.dot(Sigma.dot(v))
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
