Returns the (complex) conjugate transpose of self.

Equivalent to np.transpose(self) if self is real-valued.

In [1]:
import numpy as np

In [3]:
x = np.matrix(np.arange(12).reshape(3,4))

In [4]:
x

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [5]:
z = x - 1j*x;
z

matrix([[ 0. +0.j,  1. -1.j,  2. -2.j,  3. -3.j],
        [ 4. -4.j,  5. -5.j,  6. -6.j,  7. -7.j],
        [ 8. -8.j,  9. -9.j, 10.-10.j, 11.-11.j]])

In [6]:
z.getH()

matrix([[ 0. -0.j,  4. +4.j,  8. +8.j],
        [ 1. +1.j,  5. +5.j,  9. +9.j],
        [ 2. +2.j,  6. +6.j, 10.+10.j],
        [ 3. +3.j,  7. +7.j, 11.+11.j]])