In [1]:
#create a vector
from numpy import array

#define a vector
v = array([1, 2, 3])
print(v)

[1 2 3]


## 1.1 Vector Arithmetic

In [4]:
a = array([1, 2, 3])
b = array([1, 2, 3])

c=a+b
c

array([2, 4, 6])

## 1.2 Vector Subtraction

In [6]:
b = array([0.5, 0.5, 0.5])

c = a-b
c

array([0.5, 1.5, 2.5])

## 1.3 Vector Multiplication

In [8]:
b = array([1, 2, 3])

c = a*b
c

array([1, 4, 9])

## 1.4 Vector Division

In [9]:
# c[0] = a[0]/b[0]

In [10]:
c = a/b
c

array([1., 1., 1.])

## 1.5 Vector-Scalar Multiplication

In [12]:
s=0.5
c = s*a
print(c)

[0.5 1.  1.5]


In [13]:
# Minimum dimensions 2
array([1,2,3], ndmin=2)

array([[1, 2, 3]])

In [14]:
#Type Provided
array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [16]:
# Data-type consisting of more than one element
x = array([(1,2),(3,4)], dtype=[('a', '<i4'), ('b', '<i4')])
x['a']

array([1, 3])

In [19]:
print(x)

[(1, 2) (3, 4)]


In [23]:
#Creating an array from sub-classes:
from numpy import mat
array(mat('1 2; 3 4'))

array([[1, 2],
       [3, 4]])

In [25]:
array(mat('1 2; 3 4'), subok=True)

matrix([[1, 2],
        [3, 4]])

In [27]:
from numpy import asmatrix

In [29]:
x = array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [30]:
m = asmatrix(x)
m

matrix([[1, 2],
        [3, 4]])

In [31]:
x[0, 0] = 5

In [32]:
m

matrix([[5, 2],
        [3, 4]])