In [6]:
from numpy import array
l = [1.0, 2.0, 3.0]
a=array(l)
print(a)

[1. 2. 3.]


In [7]:
# Display array shape
a.shape

(3,)

In [8]:
# Display array data type
a.dtype

dtype('float64')

## 1. Functions to Create Array

### 1.1  Empty

In [9]:
# The values or content of the created array will be random and will need to be assigned before
#use

from numpy import empty

a = empty([3,3])
print(a)

[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 5.81021200e-321]
 [1.29061142e-306 5.11798223e-307 1.37961370e-306]]


In [17]:
a = empty([3,3], dtype=int)
print(a)

[[        0         1         0]
 [976301616       732         0]
 [      768       541         0]]


###  1.2 Zeros

In [10]:
#The zeros() function will create a new array of the specified size with the contents filled with
#zero values

from numpy import zeros

a = zeros([3,5])
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [15]:
s = (2,2)
zeros(s)

array([[0., 0.],
       [0., 0.]])

In [16]:
zeros((2,), dtype=[('x', 'i4'), ('y', 'i4')])

array([(0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

### 1.3  Ones

In [11]:
#The ones() function will create a new array of the specified size with the contents filled with
#one values.

from numpy import ones
a = ones([5])
a

array([1., 1., 1., 1., 1.])

In [18]:
a = ones([5], dtype=int)
a

array([1, 1, 1, 1, 1])