#### Array with different sizes cannot be added, subtracted, or generally be used in arithmetic.

#### A way to overcome this is to duplicate the smaller array so that it has the dimensionality and size as the larger array. This is called array broadcasting and is available in NumPy when performing array arithmetic, which can greatly reduce and simplify your code.

## 7.1 Broadcasting in Numpy

### 7.1.1 Scalar and One-Dimensional Array

In [1]:
from numpy import array

#define array
a = array([1,2,3])

#define scalar
#here b will be broadcasted to [2,2,2]

b=2 

c=a+b
c

array([3, 4, 5])

### 7.1.2  Scalar and Two-Dimensional Array

In [2]:
a = array([[1, 2, 3],
            [1, 2, 3]])

#here b will be broadcasted to [[2,2,2]
#                                [2,2,2]
b = 2

c = a+b
c

array([[3, 4, 5],
       [3, 4, 5]])

### 7.1.3 One-Dimensional and Two-Dimensional Arrays

In [6]:
a = array([[1, 2, 3],
            [1, 2, 3]])

#here b will be broadcasted to [[1,2,3]
#                               [1,2,3]]
b = array([1,2,3])   

c = a+b
c

array([[2, 4, 6],
       [2, 4, 6]])

## 7.1.4 Limitations of Broadcasting

In [7]:
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A.shape)

(2, 3)


In [8]:
b = array([1, 2])
print(b.shape)

(2,)


In [10]:
c=A+b
c

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

### In practice

In [16]:
from numpy import arange
from numpy import reshape
from numpy import ones
x = arange(4)
x

array([0, 1, 2, 3])

In [17]:
xx = x.reshape(4, 1)
xx

array([[0],
       [1],
       [2],
       [3]])

In [18]:
y = ones(5)
y

array([1., 1., 1., 1., 1.])

In [20]:
z = ones((3,4))
z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
x.shape

(4,)

In [22]:
y.shape

(5,)

In [23]:
x + y

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [30]:
(x+y).shape

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [24]:
xx.shape

(4, 1)

In [25]:
xx+y

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [26]:
(xx+y).shape

(4, 5)

In [27]:
x.shape

(4,)

In [28]:
z.shape

(3, 4)

In [29]:
(x+z).shape

(3, 4)

In [31]:
x+z

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [33]:
a = array([0.0, 10.0, 20.0, 30.0])
b = array([1.0, 2.0, 3.0])

In [34]:
from numpy import newaxis

In [35]:
a[:, newaxis] +b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [ ]:
# index operator inserts a new axis into a, 
#making it a two-dimensional 4x1 array. 
#Combining the 4x1 array with b, which has shape (3,), yields a 4x3 array