## 5.1  One-Dimensional Slicing

In [1]:
from numpy import array

data = array([11, 22, 33, 44, 55])
print(data[:])

[11 22 33 44 55]


In [2]:
print(data[0:1])

[11]


In [3]:
print(data[-2:])

[44 55]


## 5.2 Two-Dimensional Slicing

#### we can select all rows and all columns except the last one by specifying : for in the rows index, and :-1 in the columns index. 

#### x=[:, :-1]  //slicing input variable

#### y=[:-1]  //slicing output variable

In [4]:
data = array([
[11, 22, 33],
[44, 55, 66],
[77, 88, 99]])


In [6]:
x, y = data[:, :-1], data[:, -1]

In [7]:
x

array([[11, 22],
       [44, 55],
       [77, 88]])

In [8]:
y

array([33, 66, 99])

### Split Train and Test Rows

##### It is common to split a loaded dataset into separate train and test sets. This is a splitting of rows where some portion will be used to train the model and remaining portion will be used to estimate the skill of the trained model.

#### the training dataset would be all rows from the beginning to the split point.
#### train = data[:split, :]

#### the test dataset would be all rows starting from the split point to the end ofthe dimension.
#### test = data[split:, :]

In [9]:
data

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [10]:
split = 2;
train, test = data[:split, :], data[split:, :]

In [11]:
train

array([[11, 22, 33],
       [44, 55, 66]])

In [12]:
test

array([[77, 88, 99]])