In [3]:
# Example of broadcasting

In [2]:
# (4, 3)                   (4, 3)
#          == padding ==>          == result ==> (4, 3)
# (3,)                     (1, 3)

In [4]:
# (3,)                       (1, 1, 3)
#            == padding ==>             == result ==> (5, 4, 3)
# (5, 4, 3)                  (5, 4, 3)

In [5]:
# Note, however, that only left-padding with 1s is allowed. Therefore:

    
# (5,)                       (1, 1, 5)
#            == padding ==>             ==> error (5 != 3)
# (5, 4, 3)                  (5, 4, 3)

In [6]:
# (5, 4, 3)                     (1, 5, 4, 3)
#               == padding ==>                == result ==> (6, 5, 4, 3)
# (6, 5, 4, 3)                  (6, 5, 4, 3)

In [7]:
# (5, 4, 1)
#            == no padding needed ==> result ==> (5, 4, 3)
# (5, 1, 3)

In [8]:
from numpy import ones
ones((4,3))+1

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [9]:
# is the same as

one = ones((1,1))
one

array([[1.]])

In [10]:
ones((4,3)) + one

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

## Explicit broadcasting with numpy.broadcast

In [11]:
from numpy import array
macros = array([
  [0.3, 2.5, 3.5],
  [2.9, 27.5, 0],
  [0.4, 1.3, 23.9],
  [14.4, 6, 2.3]])

In [12]:
cal_per_macro = array([9, 4, 4])

In [14]:
macros.shape

(4, 3)

In [15]:
cal_per_macro.shape

(3,)

In [16]:
from numpy import broadcast

In [19]:
b = broadcast(macros, cal_per_macro)
b.shape

(4, 3)

In [24]:
for i, j in b:
    print('{0}:  {1}  {2}'.format(b.index, i, j))

1:  0.3  9
2:  2.5  4
3:  3.5  4
4:  2.9  9
5:  27.5  4
6:  0.0  4
7:  0.4  9
8:  1.3  4
9:  23.9  4
10:  14.4  9
11:  6.0  4
12:  2.3  4


### Computing outer products with broadcasting

In [25]:
from numpy import arange
from numpy import reshape

In [26]:
ten = arange(1, 11)
ten

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
ten.shape

(10,)

In [28]:
# Using Numpy's reshape method to convert the row vector into a
# column vector.
ten.reshape((10,1))

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [29]:
ten.shape

(10,)

In [31]:
ten.reshape((10,1)).shape

(10, 1)

In [32]:
# Let's see what the 'broadcast' class tells us about the resulting
# shape of broadcasting ten and its column-vector version

In [33]:
broadcast(ten, ten.reshape((10, 1))).shape

(10, 10)

In [34]:
ten * ten.reshape((10, 1))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

## Use the right tool for the job

In [35]:
macros * cal_per_macro

array([[  2.7,  10. ,  14. ],
       [ 26.1, 110. ,   0. ],
       [  3.6,   5.2,  95.6],
       [129.6,  24. ,   9.2]])

In [52]:
from numpy import sum
import numpy as np
sum(macros * cal_per_macro, axis=1)

array([ 26.7, 136.1, 104.4, 162.8])

In [53]:
## axis 

In [54]:
sum(([1,2],[3,4]))

10

In [55]:
sum(([1,2],[3,4]), axis=0)

array([4, 6])

In [56]:
sum(([1,2],[3,4]), axis=1)

array([3, 7])